source "https://rubygems.org"

# Specify your gem's dependencies in relaton_nist.gemspec
gemspec

# Use local development versions of pubid gems
gem "pubid-bsi", path: "../pubid-bsi"
gem "pubid-ccsds", path: "../pubid-ccsds"
gem "pubid-cen", path: "../pubid-cen"
gem "pubid-core", path: "../pubid-core"
gem "pubid-etsi", path: "../pubid-etsi"
gem "pubid-iec", path: "../pubid-iec"
gem "pubid-ieee", path: "../pubid-ieee"
gem "pubid-iso", path: "../pubid-iso"
gem "pubid-itu", path: "../pubid-itu"
gem "pubid-jis", path: "../pubid-jis"
gem "pubid-nist", path: "../pubid-nist"

gem "rake"
gem "rspec"
gem "rubocop-performance"
gem "rubocop-rake"
gem "rubocop-rspec"
