# frozen_string_literal: true

require "json"
require "yaml"
require "fileutils"

# Extracts scheme declarations from the live model into schema/{flavor}.yaml.
# Seed tooling for TODO.restructure/01-02; TODO.restructure/07 inverts the
# direction (the identifier classes read these files instead of carrying the
# data in constants and class methods).
class SchemeExtractor
  def initialize(flavor)
    require "pubid"
    require "pubid/export"

    @flavor = flavor.to_s
    Pubid.eager_load_flavors!
    @flavor_module = Pubid::Registry.get(@flavor)
    raise ArgumentError, "Unknown flavor: #{@flavor}" unless @flavor_module

    exporter = Pubid::Export::FlavorExporter.new(@flavor.to_sym)
    @export = JSON.parse(JSON.generate(exporter.export.to_h))
  end

  def payload
    types = @export["identifier_types"].map { |type| type_entry(type) }
    {
      "flavor" => @flavor,
      "schema_version" => "1.0.0",
      "prefixes" => own_prefixes,
      "identifier_types" => types,
    }
  end

  def write(output_dir)
    FileUtils.mkdir_p(output_dir)
    path = File.join(output_dir, "#{@flavor}.yaml")
    File.write(path, header + YAML.dump(payload))
    puts "Extracted #{payload['identifier_types'].size} types to #{path}"
  end

  private

  def own_prefixes
    if @flavor_module.const_defined?(:PREFIXES, false)
      @flavor_module.const_get(:PREFIXES).to_a
    else
      @flavor_module.prefixes
    end
  end

  def type_entry(type)
    stages = (type["typed_stages"] || []).map { |stage| stage_entry(stage) }
    {
      "key" => type["key"],
      "title" => type["title"],
      "short" => type["short"],
      "abbr" => type["abbr"],
      "typed_stages" => stages,
    }.compact
  end

  def stage_entry(stage)
    {
      "stage_code" => stage["stage_code"],
      "type_code" => stage["type_code"],
      "abbr" => stage["abbr"],
      "name" => stage["name"],
      "harmonized_stages" => stage["harmonized_stages"],
    }.compact
  end

  def header
    [
      "# Generated by rake schema:extract[#{@flavor}] - SSOT seed.",
      "# Joint prefixes live in schema/core/joint_prefixes.yaml.\n",
    ].join("\n")
  end
end

namespace :schema do
  desc "Extract scheme declarations into schema/{flavor}.yaml"
  task :extract, [:flavor] do |_t, args|
    flavor = args[:flavor] || "iso"
    output_dir = File.expand_path("../../schema", __dir__)
    SchemeExtractor.new(flavor).write(output_dir)
  end
end
