= IEEE publication identifiers ("IEEE PubID")

== Purpose

Implements a mechanism to parse and utilize IEEE publication identifers.

== Historic identifier patterns

There are at least two major "pattern series" of identifiers due to historical reasons: old (type I) and new (type II).
This implementation attempts to support both types of publication identifier patterns.

== Use cases to support

* parse an type I idetifier into components
* parse type II idetifier into components
* generate PubID from the components
* generate a filename from PubID

== Elements of the PubID

=== Publisher

|===
| Name | Abbrev

| Institute of Electrical and Electronics Engineers
| IEEE

|===

=== Report number

`{number}` - is a set of one or more digits and optional letters

=== Part

`{part}` - is a set of digits and optional letters; starts with a digit; if a letter or letters are present then they are in the end; optional

=== Subpart

`{subpart}` - is a set of digits and optional letters; optional, many subparts are possible

=== Year

`{year}` - is a set of 4 digits; optional

=== Corrigendum & Amendment

`{cor}` - is a corrigendum or an amendments with the pattern `Cor {cornum}-{year}` or `Amd {cornum}:{year}` where {cornum} is a set of digits; optional

== Pasing PubID elements

=== Type I pattern

=== Type II pattern

To parse PubID elements from the type II pattern identifiers we can use a RegEx expression:

[source,regex]
----
{
  ^IEEE\s(?<number1>\w+(\.[A-Z]\d|\sHBK)?)
  (?<part1>(\.|\s)\d{1,4}[[:alpha:],]{0,7}|-\d?[A-Z]+|-\d(?=[-.]))?
  (?<subpart11>\.\d{1,3}[a-z]?|-\d{5}[a-z]?|-\d+(?=[-:_]))?
  (?<subpart12>\.\d|-\d+(?=-))?
  (?<date1>([-:.]|_-|\s-)\d{4})?
  (\/(?<number2>([A-Z]?\d+[a-z]?|Conformance\d+))
  ((\.|-)(?<part2>\d{1,3}[a-z]?)(?!\d))?
  (\.(?<subpart21>\d{1,2}))?)?
  (\/(?<number3>\d+)(\.(?<part3>\d))?)?
  (?<date2>([-:.]|_-|\s-)\d{4})?
  ((\/|_|-|\s\/)(?<correction>(Cor|(?i)Amd(?-i))(\s|\.|\.\s)?\d{1,2})
  (?<cordate>(:|-|:-|_[A-Z][a-z]{2}_)\d{4}(-\d{4})?)?)?$
}x
----

This RegEx expession covers 99% of the PubIDs from type II bibxml-ieee https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ieee-new/[dataset].

== PubID patterns

=== Document with single PubID:

`{publisher} {number}.{part}.{subpart}.{subpart}.{subpart}-{year}/{cor}`

Samples:

* IEEE 1002-1987
* IEEE 1003.1-2001
* IEEE 1003.1-2001/Cor 1-2002
* IEEE 1073.3.1a-2000
* IEEE 11073.10101-2004/Amd 1-2017

=== Document with multiple PubIDs:

`{publisher} {number}.{part}.{subpart}.{subpart}.{subpart}-{year}/{cor}, {number}.{part}.{subpart}.{subpart}.{subpart}-{year}/{cor}`

Samples:

* IEEE 1224, 1224.1, 1327-1994