= NIST publication identifiers

== Purpose

NIST publications are numbered according to an identification scheme.

This gem implements a mechanism to parse and utilize NIST publication identifers
provided in the https://github.com/usnistgov/NIST-Tech-Pubs[NIST-Tech-Pubs]
repository.

== Historic identifier patterns

There are at least three major "pattern series" of identifiers due to historical
reasons:

* NIST publications produced by the PubID scheme (202X-)
* NIST publications produced prior to the PubID scheme (1988-)
* NBS publications, produced under the National Bureau of Standards (the
  previous name of NIST, 1901 to 1988)

This implementation attempts to support all three types of publication
identifier patterns.

== NIST PubID

NIST is currently developing a unified publication identifier scheme ("PubID")
for their technical series of publications, which allows machine-readable
identifier parts.

This scheme is described in "`Publication Identifier Syntax for NIST Technical
Series Publications`" authored by
https://www.nist.gov/people/james-foti[Jim Foti]
of the https://www.nist.gov/itl/csd[CSD, ITL], and
https://www.nist.gov/people/kathryn-miller[Kathryn Miller] and
https://www.nist.gov/people/kate-bucher[Kate Bucher] of the
https://www.nist.gov/associate-director-management-resources/staff-offices/information-services-office[ISO],
Management Resources.

NOTE: This scheme is still at proposal stage.

This gem implements the NIST PubID scheme and allows the conversion to and from
historic patterns.


== Use cases to support

PubID:

. Given a PubID (full-form title, abbreviated-form title, short-form title),
  generate the corresponding machine-readable (MR) PubID format
. Given a MR PubID:
.. generate the full-form title
.. generate the abbreviated-form title
.. generate short-form title
.. generate the DOI (which is just DOI ID + MR)

Historic compatibility:

. Parse a historic publication identifier into its components:
.. output the original publication identifier (i.e. store the contents in the
  object)
.. output a MR PubID

. Parse a historic DOI into a PubID:
.. output the original DOI (i.e. store the contents in the object)
.. output a MR PubID

== Publication identifier patterns

=== 1 "Full-form" title

Samples:

* National Institute of Standards and Technology Federal Information Processing Standards Publication 199
* National Institute of Standards and Technology Special Publication 800-27, Revision A
* National Institute of Standards and Technology Special Publication 800-39 (Second Public Draft)

(originally described in https://github.com/metanorma/metanorma-nist/issues/98)

=== 2 “Abbreviated form” title

This form is used in the Authority section.

----
Natl. Inst. Stand. Technol. {abbrev(series)} {docnumber} {part | abbrev(volume)}, {abbrev(revision)}
----

* `abbrev(series)` represent the abbreviation of the Series title
* (Note: there is no `{update-date}`)
* Abbreviate “Revision” to “Rev.” and “Volume” to “Vol.”

Examples:

* "Natl. Inst. Stand. Technol. Spec. Publ. 800-78-4"
* "Natl. Inst. Stand. Technol. Spec. Publ. 800-116”
* "Natl. Inst. Stand. Technol. Spec. Publ. 800-57 Part 1, Revision 4”


(originally from https://github.com/metanorma/metanorma-nist/issues/88)

=== 3 "Short form" title

The “short form” is used to cite the documents within text.

It is used in these situations:

1. Locality references. “In Section 3.2 of SP 800-187…” (the "SP 800-187” is a link).
+
NOTE: NIST pubs are composed of "Sections" not "Clauses"

2. A generic document reference. “SP 800-53 describes…”. This form does not specify a revision or update date.

3. “All parts”. “The SP 800-57 subseries describes key management…”.

"NISTIR 6885 2003 Edition (February 2003)” is a poor indicator.

The correct rule should be:

----
{abbrev(series)} {docnumber} {abbrev(volume)} {abbrev(revision)} {edition, optional}
----

NOTE: For FIPS, `docnumber` is the full FIPS number, including revision, e.g.,
`140-2`.

(originally from https://github.com/metanorma/metanorma-nist/issues/88)

Short form date:

* `Month YYYY`

Examples:

* NIST SP 800-53r4 (20152201) supersedes NIST SP 800-53r4 (20140115)
* NIST SP 800 63A (December 2017) supersedes NIST SP 800-63A
* NIST SP 800 57 Part 1 Revision 4 supersedes NIST SP 800-57 Part 1 Revision 3 ("Rev." is also accepted, and converted to "Revision")
* NIST SP 800 160 Volume 1 supersedes NIST SP 800-160 (20180103) ("Vol." is also accepted, and converted to "Volume")
* Undated form "NIST SP 800 53r4"

Strip Revision and Date from title, only if the Revision and Date are unique for
each document number. These are identified as "Rev. ...", "Revision ...." and "
(Month YYYY)", whichever comes first.



=== 4 Machine-readable form

The machine-readable form is:

----
NIST.{series}.{docnumber}.{part|volume}.{revision}.{update-date}
----

Generally, this rule should be able to uniquely identify an edition of a document.

Where:

----
series = SP, IR, FIPS, TN [“Technical Note”], HB [“Handbook”], CSWP [“Cybersecurity White Paper”]
----

Details:
* Various scenarios for “part”:
** “Part 1” use “pt1”;
** When a letter part is indicated, “800-63A” we should keep it as part of the docnumber (i.e., don’t indicate “pt”)

* Volumes: use “v1”

* Revision typically: “Revision 1” use “r1”

* If a superseding edition is a full revision, it will get the next Rev. #.
* If a superseding edition is just an errata update, we can use the update date
from the title page (“includes updates as of…”) to uniquely identify this
edition. Preferably use `-yyyymmdd` format.

Some examples:
* `NIST.SP.800-53r4-20152201` supersedes `NIST.SP.800-53r4-20140115`
* `NIST.SP.800-63A-20171201` supersedes `NIST.SP.800-63A`
* `NIST.SP.800-57pt1r4` supersedes `NIST.SP.800-57pt1r3`
* `NIST.SP.800-160v1` supersedes `NIST.SP.800-160-20180103`
* Undated form `NIST.SP.800-53r4`

(originally from https://github.com/metanorma/metanorma-nist/issues/88)


== NIST Series prefixes

[source,ruby]
----
SERIES_ABBR = {
  "nist-ams": "NIST AMS",
  "building-science": "NIST Building Science Series",
  "nist-fips": "NIST FIPS",
  "nist-gcr": "NISTGCR",
  "nist-hb": "NIST HB",
  "itl-bulletin": "ITL Bulletin",
  "jpcrd": "JPCRD",
  "nist-jres": "NIST JRES",
  "letter-circular": "NIST Letter Circular",
  "nist-monograph": "NIST MN",
  "nist-ncstar": "NIST NCSTAR",
  "nist-nsrds": "NIST NSRDS",
  "nistir": "NISTIR",
  "product-standards": "NIST Product Standards",
  "nist-sp": "NIST SP",
  "nist-tn": "NIST TN",
  "other": "NIST Other",
  "csrc-white-paper": "CSRC White Paper",
  "csrc-book": "CSRC Book",
  "csrc-use-case": "CSRC Use Case",
  "csrc-building-block": "CSRC Building Block",
}.freeze
----


== Addendum

NIST SP 800-38A has an Addendum.

In NIST MR let's call this part add-X, e.g. "NIST SP 800-38A Addendum" =>
`NIST.SP.800-38A.pt-A.add-1`

. Full form title: "Addendum to National Institute of Standards and Technology {series} {docnumber} {part | volume}, {revision}"

. Abbreviated form title: "Addendum to Natl. Inst. Stand. Technol. {abbrev(series)} {docnumber} {part | abbrev(volume)}, {abbrev(revision)}"

. Short form title: "{abbrev(series)} {docnumber} {part | abbrev(volume)}, {abbrev(revision)} Addendum"

. Machine-readable form NIST.SP.800-38A.pt-A.add-1

Originally from https://github.com/metanorma/metanorma-nist/issues/259.

== TODO

* Support the Supplement type