#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"
require_relative "../lib/nist_pubid"
require "thor"
require "csv"

def render_report_doc(doc)
  [doc[:finalPubId] != doc[:id],
   doc[:finalPubId],
   doc[:id],
   doc[:mr] != doc[:doi],
   doc[:mr],
   doc[:doi],
   doc[:title]]
end

class NistPubidCLI < Thor
  desc "report", "Create report for NIST Tech Pubs database (fetches from GitHub)"
  option :csv, aliases: "-c", type: :boolean, desc: "Export to CSV format"
  option :updated, aliases: "-u", type: :boolean,
                   desc: "Return only updated identifiers",
                   default: false
  def report
    heading = %w(
      ID\ changed?
      New\ PubID
      Document\ ID
      DOI\ changed?
      New\ PubID-MR
      DOI
      Title
    )
    STDERR.puts "Downloading NIST-Tech-Pubs XML database..."
    NistPubid::NistTechPubs.fetch

    if options[:csv]
      puts heading.to_csv

      NistPubid::NistTechPubs.status.each do |doc|
        puts render_report_doc(doc).to_csv
      end
    else
      puts heading.join(" | ")

      NistPubid::NistTechPubs.status.each do |doc|
        puts (render_report_doc(doc).map do |v|
          case v
          when false
            " -"
          when true
            "✅"
          else
            v
          end
        end).join(" | ")
      end
    end
  end

  desc "convert", "Convert legacy NIST Tech Pubs ID to NIST PubID"
  option :style, aliases: "-s", type: :string,
                 desc: "Convert to PubID style (short|long|mr|abbrev)",
                 default: "short"
  option :format, aliases: "-f", type: :string,
                  desc: "Render in format (json|string)",
                  default: "string"
  def convert(code)
    unless %w[mr long short abbrev].include?(options[:style].downcase)
      raise "Invalid PubID style"
    end

    raise "Invalid render format" unless %w[string json].include? options[:format].downcase

    unless code.empty?
      if options[:format] == "string"
        puts NistPubid::Document.parse(code).to_s(options[:style].to_sym)
      else
        puts NistPubid::Document.parse(code).to_json
      end
    end
  rescue NistPubid::Errors::ParseError
    puts "[Error] This does not seem to be a valid NIST Tech Pubs legacy identifier"
  end
end

NistPubidCLI.start(ARGV)
